### ISSUE TITLE
Correct display of tensorflow loading bars

### ISSUE THREAD

**Issue by AlexandreSajus** [MathisFederico/OpenCodeBlocks#51]
Only the last Tensorflow loading bar is showed when model.fit is called which means that the epoch number and the previous epochs are not shown

**Comment by AlexandreSajus** [comment]
I have no idea how to fix this currently, either we show the last output of the kernel and we don't get the previous epochs informations; or we show every output and we get the same loading bar multiple times

**Comment by MathisFederico** [comment]
Resolved by  #38

**Comment by AlexandreSajus** [comment]
There might be a way to solve this by accumulating or replacing output according to special symbols sent by the tensorflow logger such as /r carriage return or /n newline

**Comment by MathisFederico** [comment]
Closed by #79
